language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
before_script: 
  - echo "StaticUrl:http://website/" >> system/config/config.ini
  - php yellow.php version
script: 
  - php yellow.php build test
